version: 1.0
os: linux
files:
  - source: /
    destination: /home/app
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root