server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug

spring:
  profiles:
    include:
      - connection
  config:
    import: classpath:apis/api.yml, classpath:secret/inits/init.yml, classpath:cors/cors.yml
  data:
    jdbc:
      repositories.enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      encoding: UTF-8

  #  # local DB
#  datasource:
#    url: jdbc:mysql://localhost:3306/belieme
#    username: root
#    password: localTest123
#    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    basename: messages/message
    encoding: UTF-8
    cache-duration: 30
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: true